"""apply not null constraints and column changes

Revision ID: 5ab70ca4c1d4
Revises: 11cc3388b040
Create Date: 2025-12-04 19:46:14.762070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab70ca4c1d4'
down_revision: Union[str, Sequence[str], None] = '11cc3388b040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'github_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'github_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'github_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'github_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
