"""update base

Revision ID: 74e40b4db9ea
Revises: 8bcc2f535316
Create Date: 2025-12-04 19:10:15.593356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e40b4db9ea'
down_revision: Union[str, Sequence[str], None] = '8bcc2f535316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'agotchi', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agotchi', type_='unique')
    # ### end Alembic commands ###
