"""Initial migration for PostgreSQL

Revision ID: 8bcc2f535316
Revises: 
Create Date: 2025-12-01 20:55:43.387081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcc2f535316'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('github_name', sa.String(), nullable=False),
    sa.Column('github_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id'),
    sa.UniqueConstraint('github_token')
    )
    op.create_index(op.f('ix_user_github_name'), 'user', ['github_name'], unique=True)
    op.create_table('agotchi',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('last_commit_check', sa.DateTime(), nullable=False),
    sa.CheckConstraint("mood IN ('Happy', 'Angry', 'Dead')", name='agotchi_mood'),
    sa.CheckConstraint('hp <= 100', name='agotchi_hp_max'),
    sa.CheckConstraint('hp >= 0', name='agotchi_hp_mix'),
    sa.ForeignKeyConstraint(['user_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agotchi')
    op.drop_index(op.f('ix_user_github_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
